# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 830)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(860, 20, 16, 16))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-radius:8px;\n"
"    background-color: #336666;\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:8px;\n"
"    background-color: #CCCCCC;\n"
"}\n"
"\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(890, 20, 16, 16))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border-radius:8px;\n"
"    background-color: #336666;\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius:8px;\n"
"    background-color: #CCCCCC;\n"
"}\n"
"\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 1001, 811))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.listView = QtWidgets.QListView(self.tab)
        self.listView.setGeometry(QtCore.QRect(660, 140, 331, 641))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listView.setFont(font)
        self.listView.setStyleSheet("QListView{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.listView.setObjectName("listView")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(660, 90, 101, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(660, 60, 51, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(660, 30, 51, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(710, 30, 101, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(710, 60, 101, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 740, 141, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:15px;\n"
"    color:#fff;\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #99CCCC, stop:1 #336699)\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:15px;\n"
"    padding-left:15px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 740, 111, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:15px;\n"
"    color:#fff;\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #99CCCC, stop:1 #336699)\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:15px;\n"
"    padding-left:15px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(10, 70, 611, 651))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(260, 700, 141, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:15px;\n"
"    color:#fff;\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #99CCCC, stop:1 #336699)\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:15px;\n"
"    padding-left:15px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(70, 700, 111, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:15px;\n"
"    color:#fff;\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #99CCCC, stop:1 #336699)\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:15px;\n"
"    padding-left:15px;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(100, 30, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("QTextEdit{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(20, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_3.setGeometry(QtCore.QRect(100, 100, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("QTextEdit{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_4.setGeometry(QtCore.QRect(300, 200, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setStyleSheet("QTextEdit{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.textEdit_4.setObjectName("textEdit_4")
        self.listView_2 = QtWidgets.QListView(self.tab_2)
        self.listView_2.setGeometry(QtCore.QRect(620, 80, 331, 641))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listView_2.setFont(font)
        self.listView_2.setStyleSheet("QListView{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.listView_2.setObjectName("listView_2")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(620, 30, 101, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 91, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(10, 200, 91, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_5.setGeometry(QtCore.QRect(60, 200, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_5.setFont(font)
        self.textEdit_5.setStyleSheet("QTextEdit{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(220, 200, 91, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_6.setGeometry(QtCore.QRect(90, 280, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_6.setFont(font)
        self.textEdit_6.setStyleSheet("QTextEdit{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(10, 280, 91, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_7.setGeometry(QtCore.QRect(80, 370, 411, 271))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_7.setFont(font)
        self.textEdit_7.setStyleSheet("QTextEdit{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(10, 370, 91, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textEdit_8 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_8.setGeometry(QtCore.QRect(80, 140, 391, 481))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_8.setFont(font)
        self.textEdit_8.setStyleSheet("QTextEdit{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.textEdit_8.setObjectName("textEdit_8")
        self.listView_3 = QtWidgets.QListView(self.tab_3)
        self.listView_3.setGeometry(QtCore.QRect(610, 100, 331, 641))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listView_3.setFont(font)
        self.listView_3.setStyleSheet("QListView{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.listView_3.setObjectName("listView_3")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(80, 90, 91, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(610, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(100, 690, 111, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:15px;\n"
"    color:#fff;\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #99CCCC, stop:1 #336699)\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:15px;\n"
"    padding-left:15px;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(320, 690, 141, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:15px;\n"
"    color:#fff;\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #99CCCC, stop:1 #336699)\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:15px;\n"
"    padding-left:15px;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 730, 111, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:15px;\n"
"    color:#fff;\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #99CCCC, stop:1 #336699)\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:15px;\n"
"    padding-left:15px;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_10.setGeometry(QtCore.QRect(160, 730, 141, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:15px;\n"
"    color:#fff;\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #99CCCC, stop:1 #336699)\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:15px;\n"
"    padding-left:15px;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(20, 510, 181, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(690, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(850, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.listView_4 = QtWidgets.QListView(self.tab_4)
        self.listView_4.setGeometry(QtCore.QRect(690, 60, 131, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listView_4.setFont(font)
        self.listView_4.setStyleSheet("QListView{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.listView_4.setObjectName("listView_4")
        self.listView_5 = QtWidgets.QListView(self.tab_4)
        self.listView_5.setGeometry(QtCore.QRect(850, 60, 131, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listView_5.setFont(font)
        self.listView_5.setStyleSheet("QListView{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.listView_5.setObjectName("listView_5")
        self.textEdit_9 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_9.setGeometry(QtCore.QRect(20, 550, 121, 151))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_9.setFont(font)
        self.textEdit_9.setStyleSheet("QTextEdit{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.textEdit_9.setObjectName("textEdit_9")
        self.textEdit_10 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_10.setGeometry(QtCore.QRect(10, 40, 251, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_10.setFont(font)
        self.textEdit_10.setStyleSheet("QTextEdit{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.textEdit_10.setObjectName("textEdit_10")
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.listView_6 = QtWidgets.QListView(self.tab_4)
        self.listView_6.setGeometry(QtCore.QRect(10, 190, 661, 301))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listView_6.setFont(font)
        self.listView_6.setStyleSheet("QListView{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.listView_6.setObjectName("listView_6")
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(10, 150, 181, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(320, 600, 91, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.listView_7 = QtWidgets.QTextEdit(self.tab_4)
        self.listView_7.setGeometry(QtCore.QRect(400, 550, 581, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listView_7.setFont(font)
        self.listView_7.setStyleSheet("QTextEdit{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.listView_7.setObjectName("listView_7")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_24 = QtWidgets.QLabel(self.tab_5)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_5)
        self.label_25.setGeometry(QtCore.QRect(280, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_5)
        self.label_26.setGeometry(QtCore.QRect(10, 150, 231, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(280, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_5)
        self.label_28.setGeometry(QtCore.QRect(100, 140, 231, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        self.label_29.setGeometry(QtCore.QRect(640, 50, 61, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        self.label_30.setGeometry(QtCore.QRect(300, 340, 81, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.textEdit_11 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_11.setGeometry(QtCore.QRect(380, 330, 601, 441))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_11.setFont(font)
        self.textEdit_11.setStyleSheet("QTextEdit{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.textEdit_11.setObjectName("textEdit_11")
        self.listView_10 = QtWidgets.QListView(self.tab_5)
        self.listView_10.setGeometry(QtCore.QRect(280, 70, 331, 251))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listView_10.setFont(font)
        self.listView_10.setStyleSheet("QListView{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.listView_10.setObjectName("listView_10")
        self.listView_11 = QtWidgets.QListView(self.tab_5)
        self.listView_11.setGeometry(QtCore.QRect(10, 180, 91, 601))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listView_11.setFont(font)
        self.listView_11.setStyleSheet("QListView{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.listView_11.setObjectName("listView_11")
        self.listView_9 = QtWidgets.QListView(self.tab_5)
        self.listView_9.setGeometry(QtCore.QRect(10, 40, 161, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listView_9.setFont(font)
        self.listView_9.setStyleSheet("QListView{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.listView_9.setObjectName("listView_9")
        self.listView_12 = QtWidgets.QListView(self.tab_5)
        self.listView_12.setGeometry(QtCore.QRect(110, 180, 151, 401))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listView_12.setFont(font)
        self.listView_12.setStyleSheet("QListView{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.listView_12.setObjectName("listView_12")
        self.listView_8 = QtWidgets.QListView(self.tab_5)
        self.listView_8.setGeometry(QtCore.QRect(640, 90, 291, 231))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listView_8.setFont(font)
        self.listView_8.setStyleSheet("QListView{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.listView_8.setObjectName("listView_8")
        self.textEdit_12 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_12.setGeometry(QtCore.QRect(800, 30, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_12.setFont(font)
        self.textEdit_12.setStyleSheet("QTextEdit{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.textEdit_12.setObjectName("textEdit_12")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_11.setGeometry(QtCore.QRect(110, 730, 111, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:15px;\n"
"    color:#fff;\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #99CCCC, stop:1 #336699)\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:15px;\n"
"    padding-left:15px;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_12.setGeometry(QtCore.QRect(230, 730, 141, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:15px;\n"
"    color:#fff;\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #99CCCC, stop:1 #336699)\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:15px;\n"
"    padding-left:15px;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_31 = QtWidgets.QLabel(self.tab_5)
        self.label_31.setGeometry(QtCore.QRect(800, 0, 141, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.textEdit_13 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_13.setGeometry(QtCore.QRect(110, 590, 101, 131))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit_13.setFont(font)
        self.textEdit_13.setStyleSheet("QTextEdit{\n"
"background:#fff;\n"
"border:1px solid #000;\n"
"border-radius:10px;\n"
"}\n"
"")
        self.textEdit_13.setObjectName("textEdit_13")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 1001, 41))
        self.label_8.setStyleSheet("background:rgb(218,218,218);\n"
"border-top-left-radius:30px;\n"
"border-top-right-radius:30px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_8.raise_()
        self.tabWidget.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "输出:"))
        self.label_4.setText(_translate("MainWindow", "char:"))
        self.label_3.setText(_translate("MainWindow", "row:"))
        self.pushButton_3.setText(_translate("MainWindow", "词法分析"))
        self.pushButton_4.setText(_translate("MainWindow", "清空"))
        self.label_7.setText(_translate("MainWindow", "编辑区:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "词法分析器"))
        self.pushButton_5.setText(_translate("MainWindow", "开始转换"))
        self.pushButton_6.setText(_translate("MainWindow", "清空"))
        self.label_9.setText(_translate("MainWindow", "NFA状态集:"))
        self.label_10.setText(_translate("MainWindow", "输出:"))
        self.label_11.setText(_translate("MainWindow", "符号集:"))
        self.label_12.setText(_translate("MainWindow", "初态:"))
        self.label_13.setText(_translate("MainWindow", "终态:"))
        self.label_14.setText(_translate("MainWindow", "弧的条数:"))
        self.label_15.setText(_translate("MainWindow", "弧:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "NFA"))
        self.label_16.setText(_translate("MainWindow", "请输入文法:"))
        self.label_17.setText(_translate("MainWindow", "First集合:"))
        self.pushButton_7.setText(_translate("MainWindow", "清空"))
        self.pushButton_8.setText(_translate("MainWindow", "开始计算"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "First集合计算"))
        self.pushButton_9.setText(_translate("MainWindow", "清空"))
        self.pushButton_10.setText(_translate("MainWindow", "分析"))
        self.label_18.setText(_translate("MainWindow", "表达式文法:"))
        self.label_19.setText(_translate("MainWindow", "FirstVT集合:"))
        self.label_20.setText(_translate("MainWindow", "LastVT集合:"))
        self.textEdit_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">E -&gt; E+T</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">E -&gt; E-T</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">E -&gt; T</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">T -&gt; T*F</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">T -&gt; T/F</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">T -&gt; F</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">F -&gt; (E)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">F -&gt; i</p></body></html>"))
        self.textEdit_10.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.textEdit_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "请输入待分析的字符串表达式:"))
        self.label_22.setText(_translate("MainWindow", "算符优先分析表:"))
        self.label_23.setText(_translate("MainWindow", "分析结果:"))
        self.listView_7.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.listView_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "算符优先表达式分析器"))
        self.label_24.setText(_translate("MainWindow", "Follow集合："))
        self.label_25.setText(_translate("MainWindow", "SLR（1）分析表"))
        self.label_26.setText(_translate("MainWindow", "状态集合："))
        self.label_27.setText(_translate("MainWindow", "Action："))
        self.label_28.setText(_translate("MainWindow", "状态转移集合："))
        self.label_29.setText(_translate("MainWindow", "Goto："))
        self.label_30.setText(_translate("MainWindow", "分析结果："))
        self.textEdit_11.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.textEdit_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_12.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.textEdit_12.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_11.setText(_translate("MainWindow", "清空"))
        self.pushButton_12.setText(_translate("MainWindow", "分析"))
        self.label_31.setText(_translate("MainWindow", "待分析字符串输入："))
        self.textEdit_13.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.textEdit_13.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">S-&gt;E</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">E-&gt;(L)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">E-&gt;a</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">L-&gt;L,E</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">L-&gt;E</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "SLR (1) 语法分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "页"))
